### PR TITLE
fix: Handle NoSuchElementException when Ctrl-C termination

### LINKED ISSUE #231: NoSuchElementException when program is terminated with Ctrl-C
MediTracker program shows a NoSuchElement error message when terminated with Ctrl-C.

### PR DESCRIPTION
**Pull request by nickczh**
# Checklist for feature implementation and modification
Closes #231 
- [x] Added relevant milestone (under milestone tab on the right)
- Implementation
  - [ ] Sources (if any) credited under both relevant section(s) and Developer Guide (Acknowledgement)
  - [ ] JUnit Test(s)
- Documentation
  - [x] JavaDoc for classes and methods
  - Developer Guide
    - [ ] Design (Can add as a todo statement for later on)
    - [ ] Implementation (Can add as a todo statement for later on)
    - [ ] Relevant User Story present
    - [ ] Non-functional requirement(s) that the feature addresses (if any)
    - [ ] Glossary of the (technical) term(s) used (if any)
    - [ ] Specialised instructions for manual testing (if any)
  - User Guide
    - [ ] Description and usage of feature (if any)
  - Contributions (under `/docs/team/*.md`)
    - [ ] Code/Feature/Enhancement contribution
    - [ ] Developer Guide contribution
    - [ ] User Guide contribution
    - [ ] Misc and team-based admin tasks (if any)

# Checklist for non-implementation related PR
Closes #<Issue_Number>
- [ ] Added relevant milestone (under milestone tab on the right)
- Documentation (Contributions)
  - [ ] Developer Guide contributions (if any)
  - [ ] User Guide contributions (if any)
  - [ ] Review contributions (if any)
  - [ ] Miscellaneous and team-based admin tasks (if any)

# Additional Information

Nil

### CODE REVIEW

File: src/main/java/meditracker/ui/Ui.java [hunk 1]
```diff
@@ -113,12 +114,22 @@ public static void showInfoMessage(String message) {
...
 
     /**
-     * Reads user input command.
-     * @return The user input command as a String.
+     * Reads a command from the user input, prompting with "meditracker> ".
+     * This method continuously waits and reads user input until a command is entered.
+     * If there is no more input (end of stream), the method will display an exit message and terminate the program.
+     *
+     * @return The input entered by the user. If the program terminates due to no more input, null is returned.
+     * @throws NoSuchElementException if the input stream is closed and no more tokens are available for retrieval.
```
Comment (wenenhoe) [inline src/main/java/meditracker/ui/Ui.java:122]: Exception mentioned here is not thrown, but caught and handled. Do remove it from the javadoc.

**Review by wenenhoe — CHANGES_REQUESTED** [review]
Good catch on handling the Ctrl-C termination! Just a minor change on the javadoc required.

File: src/main/java/meditracker/ui/Ui.java (hunk 1 above)
Comment (nickczh) [reply src/main/java/meditracker/ui/Ui.java]: Resolved in 83b7cb039b8f79315a593e8567d8babf556d3865. Thanks!

**Review by wenenhoe — APPROVED** [review]
