### PR TITLE
[#226] Fix saving and loading to include DailyMedication

### LINKED ISSUE #226: bug: Make saving of medication also save dailyMedication
Right now, the `load` and `save` function only saves the to the JSON file, while the dailyMedication information are not affected. This is a potential bug that needs to be addressed.

### PR DESCRIPTION
**Pull request by annoy-o-mus**
# Checklist for feature implementation and modification
Closes #226 
- [X] Added relevant milestone (under milestone tab on the right)
- Implementation
  - [X] Sources (if any) credited under both relevant section(s) and Developer Guide (Acknowledgement)
  - [ ] JUnit Test(s)
- Documentation
  - [X] JavaDoc for classes and methods
  - Developer Guide
    - [ ] Design (Can add as a todo statement for later on)
    - [ ] Implementation (Can add as a todo statement for later on)
    - [ ] Relevant User Story present
    - [ ] Non-functional requirement(s) that the feature addresses (if any)
    - [ ] Glossary of the (technical) term(s) used (if any)
    - [ ] Specialised instructions for manual testing (if any)
  - Contributions (under `/docs/team/*.md`)
    - [X] Code/Feature/Enhancement contribution
    - [ ] Developer Guide contribution
    - [ ] User Guide contribution
    - [ ] Misc and team-based admin tasks (if any)

# Additional Information
Previously, the `load` and `save` only works on `Medication` JSON data. This creates potential problem when loading `Medication` while `DailyMedication` remains unaffected, resulting in potential compatibility issues.

The change is made such that now when using the `load` and `save` command, the corresponding `DailyMedication` data gets saved and loaded too

Also Streamlines some loading and saving functionality

### CODE REVIEW

File: src/main/java/meditracker/command/SaveCommand.java [hunk 1]
```diff
@@ -46,33 +46,56 @@ public SaveCommand(String arguments)
...
+     * Includes the Medication data (in JSON) and DailyMedication data (in txt).
      */
-    private void saveJsonToDefaultLocation() {
-        boolean isSaveSuccessful = FileReaderWriter.saveMediTrackerData(null);
+    private void saveToDefaultLocation() {
+        boolean isSaveSuccessful = FileReaderWriter.saveMedicationData(null);
         if (!isSaveSuccessful) {
-            System.out.println("An error occurred while saving. Data is not saved.");
+            System.out.println("An error occurred while saving Medication data. Data is not saved.");
+            return;
```
Comment (wenenhoe) [inline src/main/java/meditracker/command/SaveCommand.java:56]: Since both saving process should remain independent (i.e. should attempt saveDailyMedicationData), even if saveMedicationData fails, code should not return here.

File: src/main/java/meditracker/command/SaveCommand.java [hunk 2]
```diff
@@ -46,33 +46,56 @@ public SaveCommand(String arguments)
...
+     * @param jsonSaveFilePath The location of the JSON file to save to.
      */
-    private void saveJsonToSpecifiedLocation(Path saveFilePath) {
-        boolean isSaveSuccessful = FileReaderWriter.saveMediTrackerData(saveFilePath);
+    private void saveToSpecifiedLocation(Path jsonSaveFilePath) {
+        boolean isSaveSuccessful = FileReaderWriter.saveMedicationData(jsonSaveFilePath);
         if (!isSaveSuccessful) {
-            System.out.println("An error occurred while saving. Data is not saved.");
+            System.out.println("An error occurred while saving Medication Data. Data is not saved.");
+            return;
```
Comment (wenenhoe) [inline src/main/java/meditracker/command/SaveCommand.java:85]: Same here. Since both saving process should remain independent (i.e. should attempt saveDailyMedicationData), even if saveMedicationData fails, code should not return here.

**Review by wenenhoe — CHANGES_REQUESTED** [review]
Thanks for helping to refactor and clean up the saving and loading process. Identified some potential issues with the code. Do have a look.

File: src/main/java/meditracker/command/SaveCommand.java (hunk 1 above)
Comment (annoy-o-mus) [reply src/main/java/meditracker/command/SaveCommand.java]: resolved: e8ab6759f4e39b486aa4286098edb631b93bc509

File: src/main/java/meditracker/command/SaveCommand.java (hunk 2 above)
Comment (annoy-o-mus) [reply src/main/java/meditracker/command/SaveCommand.java]: resolved: e8ab6759f4e39b486aa4286098edb631b93bc509

**Review by wenenhoe — APPROVED** [review]
