### PR TITLE
[#241] fix code quality

### LINKED ISSUE #241: fix: code quality for annoy-o-mus

### PR DESCRIPTION
**Pull request by annoy-o-mus**
# Checklist for non-implementation related PR
Closes #241

### CODE REVIEW

File: src/main/java/meditracker/dailymedication/DailyMedicationManager.java [hunk 1]
```diff
@@ -50,6 +51,7 @@ public static void createDailyMedicationManager() {
      * @param lines lines of String read from each row in the textfile
      */
     public static void importDailyMedicationManager(List<String> lines) {
+        clearDailyMedication(); // For when loading from save file
```
Comment (T0nyLin) [inline src/main/java/meditracker/dailymedication/DailyMedicationManager.java:54]: Oh this was my fault, I forgot I removed them when I merged my branch. Thanks for catching my mistake!

File: src/main/java/meditracker/storage/FilePathChecker.java [hunk 2]
```diff
@@ -151,18 +151,17 @@ public static boolean isValidFullPath(Path path) {
...
     }
 
     /**
-     * Validates the path input and return the Path object if successfully validated.
+     * Validates the string input and return the Path object if successfully validated.
      *
-     * @param fileLocationArgument The argument specifying the location of the file (as String)
-     * @return The Path object corresponding to the argument for the save file if it passes validation checks.
+     * @param fileLocationArgument The argument specifying the location of the file (as String).
+     * @return The Path object corresponding to the string argument for the save file if it passes validation checks,
```
Comment (T0nyLin) [inline src/main/java/meditracker/storage/FilePathChecker.java:161]: Should be fullstop, not comma

**Review by T0nyLin — CHANGES_REQUESTED** [review]
Good code quality checks and refactoring! Just a punctuation mistake.

File: src/main/java/meditracker/storage/FilePathChecker.java (hunk 2 above)
Comment (annoy-o-mus) [reply src/main/java/meditracker/storage/FilePathChecker.java:161]: there is further text "null otherwise" after the comma actually which is not modified (L162)

Comment (T0nyLin) [reply src/main/java/meditracker/storage/FilePathChecker.java:161]: Sry my bad.
