### PR TITLE
fix(style): Fix style

### LINKED ISSUE #151: wenenhoe - stricter styling checks

### PR DESCRIPTION
**Pull request by wenenhoe**
# Checklist for non-implementation related PR
Closes #151 
- [x] Added relevant milestone (under milestone tab on the right)
- Documentation (Contributions)
  - [ ] Developer Guide contributions (if any)
  - [ ] User Guide contributions (if any)
  - [ ] Review contributions (if any)
  - [ ] Miscellaneous and team-based admin tasks (if any)

### CODE REVIEW

File: src/main/java/meditracker/argument/AfternoonArgument.java [hunk 1]
```diff
@@ -4,6 +4,12 @@
  * Argument to represent afternoon
  */
 public class AfternoonArgument extends Argument {
+
+    /**
+     * Constructs an AfternoonArgument with whether it is optional
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/argument/AfternoonArgument.java:9]: Suggestion: "with whether the argument is optional"

File: src/main/java/meditracker/argument/EveningArgument.java [hunk 2]
```diff
@@ -4,6 +4,12 @@
  * Argument to represent evening
  */
 public class EveningArgument extends Argument {
+
+    /**
+     * Constructs an EveningArgument with whether it is optional
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/argument/EveningArgument.java:9]: Suggestion "whether the argument is optional", same for all similar arguments

File: src/main/java/meditracker/exception/ArgumentException.java [hunk 3]
```diff
@@ -1,5 +1,8 @@
 package meditracker.exception;
 
+/**
+ * Exception thrown when ArgumentParser encounters an argument-related error
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/exception/ArgumentException.java:4]: Missing full stop, also missing in argument javadocs

File: src/main/java/meditracker/exception/InsufficientQuantityException.java [hunk 4]
```diff
@@ -1,9 +1,18 @@
 package meditracker.exception;
 
+/**
+ * Exception thrown when Medication object has insufficient quantity available to take medication
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/exception/InsufficientQuantityException.java:4]: Missing full stop

File: src/main/java/meditracker/ui/Ui.java [hunk 5]
```diff
@@ -83,30 +83,65 @@ public static void showExitMessage() {
         System.out.println("Thank you for using MediTracker. Hope to see you again!");
     }
 
+    /**
+     * Prints success message onto console. Prepends success message with
+     * <code>SUCCESS: </code>.
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/ui/Ui.java:88]: HTML tags generally not needed for JavaDocs

File: src/test/java/meditracker/argument/ArgumentListTest.java [hunk 6]
```diff
@@ -59,8 +60,8 @@ void parse_missingArgumentSpecified_argumentException() {
         String testArgumentString = String.format("-n %s -dM %s", name, dosage);
 
         assertThrows(
-                ArgumentException.class,
-                () -> testArgumentList.parse(testArgumentString)
+                ArgumentException.class, (
+                ) -> testArgumentList.parse(testArgumentString)
```
Comment (annoy-o-mus) [inline src/test/java/meditracker/argument/ArgumentListTest.java:64]: Does the style check allow

```
ArgumentException.class, () -> testArgumentList.parse(testArgumentString)
```

or 

```
ArgumentException.class, () 
        -> testArgumentList.parse(testArgumentString)
```

or
```
ArgumentException.class, () ->
        testArgumentList.parse(testArgumentString)
```

**Review by annoy-o-mus — CHANGES_REQUESTED** [review]
Please see the review for suggested changes

File: src/test/java/meditracker/argument/ArgumentListTest.java (hunk 6 above)
Comment (annoy-o-mus) [reply src/test/java/meditracker/argument/ArgumentListTest.java:64]: Same applies to similar changes you have made

File: src/main/java/meditracker/time/TimeRange.java [hunk 7]
```diff
@@ -2,10 +2,19 @@
 
 import java.time.LocalTime;
 
+/**
+ * Manages a start and end time, to maintain information on a time range
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/time/TimeRange.java:6]: Missing fullstops

**Review by annoy-o-mus — CHANGES_REQUESTED** [review]

**Review by annoy-o-mus — APPROVED** [review]
