### PR TITLE
Obj for each sub list

### LINKED ISSUE #105: bug: Separate dailyMedication Object for items in each sub list
Since the same object was used for each of the M/A/E sublists, when one item is marked, the same item in the other sublist(s) is/are marked as well, which is not the intention, as the 3 sublists should be independent.
Credit: @wenenhoe for finding the bug

### LINKED ISSUE #110: bug: AddCommand crashes when repeat is not supplied
Furthermore, based on the help message alone, the description for `-rep repeat` misleads users to key in a string rather than a numerical value.

### PR DESCRIPTION
**Pull request by T0nyLin**
# Checklist for feature implementation and modification
Fixes #105 and fixes #110 
- [ ] Added relevant milestone (under milestone tab on the right)
- Implementation
  - [ ] Sources (if any) credited under both relevant section(s) and Developer Guide (Acknowledgement)
  - [X] JUnit Test(s)
- Documentation
  - [ ] JavaDoc for classes and methods
  - Developer Guide
    - [ ] Design (Can add as a todo statement for later on)
    - [ ] Implementation (Can add as a todo statement for later on)
    - [ ] Relevant User Story present
    - [ ] Non-functional requirement(s) that the feature addresses (if any)
    - [ ] Glossary of the (technical) term(s) used (if any)
    - [ ] Specialised instructions for manual testing (if any)
  - User Guide
    - [ ] Description and usage of feature (if any)
  - Contributions (under `/docs/team/*.md`)
    - [ ] Code/Feature/Enhancement contribution
    - [ ] Developer Guide contribution
    - [ ] User Guide contribution
    - [ ] Misc and team-based admin tasks (if any)

# Checklist for non-implementation related PR
Closes #105 and closes #110 
- [ ] Added relevant milestone (under milestone tab on the right)
- Documentation (Contributions)
  - [ ] Developer Guide contributions (if any)
  - [ ] User Guide contributions (if any)
  - [ ] Review contributions (if any)
  - [ ] Miscellaneous and team-based admin tasks (if any)

# Additional Information

Nil

### CODE REVIEW

File: src/main/java/meditracker/MediTracker.java [hunk 1]
```diff
@@ -77,7 +78,7 @@ public void run() {
 
             try {
                 command.execute();
-            } catch (InvalidArgumentException e) {
+            } catch (InvalidArgumentException | MediTrackerException e) {
```
Comment (e0958902) [inline src/main/java/meditracker/MediTracker.java:81]: Id suggest @wenenhoe to review as he may have handled a similar exception in his previous PR, as discussed in our recent group meeting.

**Review by e0958902 — COMMENTED** [review]
The rest of PR changes looks good to me.

**Review by e0958902 — APPROVED** [review]
LGTM
