### PR TITLE
misc: Add tests and handle exceptions

### LINKED ISSUE #94: bug: Program crashes when provided empty arguments
When the user types `list -t` the program crashes.

### LINKED ISSUE #102: bug: Program crashes when provided with invalid index
It happens in a few cases
1. When the user types in the wrong index number (`take -l 200000`)
2. When the user types in the right index number, but the system couldnt find the medication to take at that time. 
i.e. `take -l 1` has a valid dosage to take for morning and afternoon, but not evening. Medication 1 is valid. When this command is triggered in the morning or afternoon, it runs fine. But when this is run at night, an `IndexOutOfBounds` exception may be thrown.

### LINKED ISSUE #118: feat: Enhance Ui to have methods to print different types of messages
Allow printing of error, success and warning messages with Ui

### LINKED ISSUE #119: misc: Add tests and handle exceptions
Handle index of bound, missing medication, unknown arguments, arguments with no value specified

### LINKED ISSUE #120: fix(bug): Add missing logic to modify and delete command
- Modify name of Medication did not modify name if they exist in DailyMedication
- Delete Medication did not delete DailyMedication

### PR DESCRIPTION
**Pull request by wenenhoe**
# Checklist for feature implementation and modification
Fixes #94, fixes #102, fixes #120 and closes #118, closes #119
- [x] Added relevant milestone (under milestone tab on the right)
- Implementation
  - [ ] Sources (if any) credited under both relevant section(s) and Developer Guide (Acknowledgement)
  - [x] JUnit Test(s)
- Documentation
  - [x] JavaDoc for classes and methods
  - Developer Guide
    - [ ] Design (Can add as a todo statement for later on)
    - [ ] Implementation (Can add as a todo statement for later on)
    - [ ] Relevant User Story present
    - [ ] Non-functional requirement(s) that the feature addresses (if any)
    - [ ] Glossary of the (technical) term(s) used (if any)
    - [ ] Specialised instructions for manual testing (if any)
  - User Guide
    - [ ] Description and usage of feature (if any)
  - Contributions (under `/docs/team/*.md`)
    - [ ] Code/Feature/Enhancement contribution
    - [ ] Developer Guide contribution
    - [ ] User Guide contribution
    - [ ] Misc and team-based admin tasks (if any)

# Additional Information

Nil

### CODE REVIEW

File: src/main/java/meditracker/ui/Ui.java [hunk 1]
```diff
@@ -62,7 +64,8 @@ public static void showLine() {
      */
     public static void showWelcome() {
         System.out.println("Welcome to MediTracker, your best companion to track your medicine intake.");
-        System.out.println("Let's begin tracking!\n");
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/ui/Ui.java:65]: Great catch on the improper use of `\n` as a new line

File: src/main/java/meditracker/MediTracker.java [hunk 2]
```diff
@@ -67,20 +66,16 @@ public void run() {
             Command command;
             try {
                 command = commandParser.getCommand();
-            } catch (ArgumentNotFoundException | DuplicateArgumentFoundException | CommandNotFoundException e) {
-                System.out.println(e.getMessage());
+            } catch (ArgumentNotFoundException | DuplicateArgumentFoundException | CommandNotFoundException |
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/MediTracker.java:69]: Maybe you can consider having a parent class `ArgumentException` and have these exceptions `extend` from it

File: src/main/java/meditracker/argument/ArgumentParser.java [hunk 3]
```diff
@@ -59,6 +67,32 @@ public void checkForMissingRequiredArguments() throws ArgumentNotFoundException
...
+     *
+     * @param rawInputSplit List of raw input split by spaces
+     * @throws UnknownArgumentFoundException When unknown argument flags found in user input
+     */
+    public void checkForUnknownArguments(List<String> rawInputSplit) throws UnknownArgumentFoundException {
+        List<String> argumentFlags = argumentList.getArguments().stream()
+                .map(Argument::getFlag)
+                .collect(Collectors.toList());
+
+        String pattern = "^-.+$";
```
Comment (annoy-o-mus) [inline src/main/java/meditracker/argument/ArgumentParser.java:83]: It will be great if you could provide a description as to what this regex aims to match (either as a comment or a descriptive variable name)

**Review by annoy-o-mus — APPROVED** [review]
Looks ok to go for me. Just a couple of readability recommendations for consideration. They can be implemented as a separate issue at a later stage.

File: src/main/java/meditracker/MediTracker.java (hunk 2 above)
Comment (wenenhoe) [reply src/main/java/meditracker/MediTracker.java:69]: Opened #123 in regards to this. Thanks for this suggestion.

File: src/main/java/meditracker/argument/ArgumentParser.java (hunk 3 above)
Comment (wenenhoe) [reply src/main/java/meditracker/argument/ArgumentParser.java]: Resolved in 10ac337
