### PR TITLE
fix(bug): Fix number format exception for `modify`, `delete`, `take`, `untake`

### LINKED ISSUE #154: [PE-D][Tester C] Exception unhandled for modify command
When the command modify -l listIndex is used, there should be an exception 'unknown argument'. However, the exception is unhandled and causes the program to crash, exiting the program

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cayennegoh/ped#1

### LINKED ISSUE #155: [PE-D][Tester E] NumberFormatException occurs when setting listIndex as a String
When performing the command `modify -l string`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: itsmejr257/ped#3

### LINKED ISSUE #156: [PE-D][Tester E] NumberFormatException occurs when listIndex is a string in `take -l linstIndex`
When performing the command `take -l string`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: itsmejr257/ped#4

### LINKED ISSUE #179: [PE-D][Tester B] 'modify' command does not handle non-numerical values
The _'modify -l listIndex'_ command correctly handles an out of bounds numerical value _listIndex_:

However, when a non-numerical value is provided for _listIndex_, an exception arises that is not handled:

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LWachtel1/ped#3

### LINKED ISSUE #194: [PE-D][Tester D] Exception thrown for incorrect format of delete
NumberFormatException given for command `delete -l 4 [-h]`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: fxe025/ped#8

### LINKED ISSUE #195: [PE-D][Tester B] 'take' command does not handle non-numerical values
_'take -l listIndex'_ does not handle non-numerical values for _listIndex_

Photo below shows _'take'_ help menu, correct handling of out-of-bounds numerical listIndex then failure to handle non-numerical listIndex:

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LWachtel1/ped#5

### LINKED ISSUE #204: [PE-D][Tester B] 'delete' command does not handle non-numerical listIndex
If you provided _'delete -l listIndex'_ with a non-numerical value for _listIndex_, it cannot handle the exception that arises.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LWachtel1/ped#7

### PR DESCRIPTION
**Pull request by wenenhoe**
# Checklist for feature implementation and modification
`modify`: Fixes #154, fixes #155, fixes #179
`delete`: Fixes #194, fixes #204 
`take`: Fixes #156, fixes #195 
- [x] Added relevant milestone (under milestone tab on the right)
- Implementation
  - [ ] Sources (if any) credited under both relevant section(s) and Developer Guide (Acknowledgement)
  - [x] JUnit Test(s)
- Documentation
  - [x] JavaDoc for classes and methods
  - Developer Guide
    - [ ] Design (Can add as a todo statement for later on)
    - [ ] Implementation (Can add as a todo statement for later on)
    - [ ] Relevant User Story present
    - [ ] Non-functional requirement(s) that the feature addresses (if any)
    - [ ] Glossary of the (technical) term(s) used (if any)
    - [ ] Specialised instructions for manual testing (if any)
  - User Guide
    - [ ] Description and usage of feature (if any)
  - Contributions (under `/docs/team/*.md`)
    - [x] Code/Feature/Enhancement contribution
    - [ ] Developer Guide contribution
    - [ ] User Guide contribution
    - [x] Misc and team-based admin tasks (if any)

# Additional Information
- Refactor obtaining list index and period to static methods in `Command` class

### CODE REVIEW

File: src/main/java/meditracker/command/UntakeCommand.java [hunk 1]
```diff
@@ -84,6 +74,7 @@ public void execute() {
                     "Unable to increase Medication quantity as object not found");
```
Comment (T0nyLin) [inline src/main/java/meditracker/command/UntakeCommand.java:74]: I think can just say medication is not found. "increase" and "object" does not mean much to the user.

File: src/main/java/meditracker/command/TakeCommand.java [hunk 2]
```diff
@@ -55,27 +54,17 @@ public TakeCommand(String arguments)
...
-        boolean isEvening = parsedArguments.get(ArgumentName.EVENING) != null;
-        Period period = Period.getPeriod(isMorning, isAfternoon, isEvening);
-        if (period == Period.NONE) {
-            period = Period.getPeriod(MediTrackerTime.getCurrentTime());
-        }
-
+        Period period = Command.getPeriod(parsedArguments);
         if (period == Period.UNKNOWN) {
             Ui.showErrorMessage("Unable to determine time period. " +
                     "Please select 1 flag only or try again later.");
```
Comment (T0nyLin) [inline src/main/java/meditracker/command/TakeCommand.java:63]: Instead of please select 1 flag, maybe the error message can guide the user by presenting the options such as "Please specify one of the following flags: -m/-a/-e".

File: src/main/java/meditracker/command/UntakeCommand.java [hunk 3]
```diff
@@ -57,23 +56,14 @@ public UntakeCommand(String arguments)
...
-        boolean isEvening = parsedArguments.get(ArgumentName.EVENING) != null;
-        Period period = Period.getPeriod(isMorning, isAfternoon, isEvening);
-        if (period == Period.NONE) {
-            period = Period.getPeriod(MediTrackerTime.getCurrentTime());
-        }
-
+        Period period = Command.getPeriod(parsedArguments);
         if (period == Period.UNKNOWN) {
             Ui.showErrorMessage("Unable to determine time period. " +
                     "Please select 1 flag only or try again later.");
```
Comment (T0nyLin) [inline src/main/java/meditracker/command/UntakeCommand.java:62]: Same as above in TakeCommand

**Review by T0nyLin — CHANGES_REQUESTED** [review]
Thank you for the swift fixes on the bugs! Please see the recommended changes.

File: src/main/java/meditracker/command/UntakeCommand.java (hunk 3 above)
Comment (wenenhoe) [reply src/main/java/meditracker/command/UntakeCommand.java]: Resolved in e3efe25

File: src/main/java/meditracker/command/UntakeCommand.java (hunk 1 above)
Comment (wenenhoe) [reply src/main/java/meditracker/command/UntakeCommand.java]: Partially resolved in e3efe25
I believe user should understand the context of why this warning is shown to them so I have reworded slightly to be more user friendly

Comment (T0nyLin) [reply src/main/java/meditracker/command/UntakeCommand.java]: I mean in the context of untaking a medication (which usually happens when they accidentally check off the wrong meds), the message saying "increase medication quantity" is not a deliberate/intentional from user. 
So it could lead to the user questioning "why am I trying to increase medication quantity? I am just trying to uncheck the medicine."
So in a sense, that information is not necessary to inform them.

File: src/main/java/meditracker/command/TakeCommand.java [hunk 4]
```diff
@@ -85,10 +74,11 @@ public void execute() {
             Ui.showErrorMessage(e);
             return;
         } catch (MedicationNotFoundException e) {
-            Ui.showWarningMessage("Possible corruption of data. " +
-                    "Unable to increase Medication quantity as object not found");
+            Ui.showWarningMessage("Possible data corruption: " +
+                    "Unable to decrease quantity as Medication not found");
```
Comment (T0nyLin) [inline src/main/java/meditracker/command/TakeCommand.java:78]: Yes, it make sense for this "TakeCommand", not so much for "UntakeCommand"

File: src/main/java/meditracker/command/UntakeCommand.java (hunk 1 above)
Comment (wenenhoe) [reply src/main/java/meditracker/command/UntakeCommand.java]: Resolved in 1d7d633

**Review by T0nyLin — APPROVED** [review]
LGTM! Thx for the bug fixes and changes!
